version: '3.5'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    network_mode: host
    restart: always
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      # данные для подключения к базе должны совпадать с данными из  local.yml
      MYSQL_ROOT_PASSWORD: Ky43IEGSo8rs
      MYSQL_DATABASE: comics
      MYSQL_USER: advita
      MYSQL_PASSWORD: Ky43IEGSo8rs
    command:
      - '--secure-file-priv='

  migrate:
    container_name: migrate
    build:
      context: .
      dockerfile: Dockerfile-migrate
    network_mode: host
    restart: on-failure
    volumes:
      - ./local.yml:/root/local.yml
    depends_on:
      - mysql

  http:
    container_name: http
    build:
      context: .
      dockerfile: Dockerfile-http
    network_mode: host
    restart: always
    volumes:
      - ./local.yml:/root/local.yml
    depends_on:
      - mysql
      - migrate
